### ISSUE TITLE
Nested filtering with child element property and collection combination

### ISSUE THREAD

**Issue by MichalVlcek** [alirezanet/Gridify#75]
### Version
2.7.1
### Details
Hi, 

I'm having a problem with a nested collection filtering. Take for example this class structure:
```
public class Root
{
    public Child1 Child1 { get; set; }
    public IEnumerable<Child2> Child2List { get; set; }
}

public class Child1
{
    public IEnumerable<Child2> Child2List { get; set; }
}

public class Child2
{
    public string Name { get; set; }
}
```
Then create mapping like this:
```
var mapping = new GridifyMapper<Root>()
            .AddMap("Child2Name", x => x.Child2List.Select(c => c.Name)) // Works fine
            .AddMap("Child2NameNested", x => x.Child1.Child2List.Select(c => c.Name)); // Throws exception
```
Then generate filtering expression.
```
new GridifyQuery {Filter = "Child2NameNested=name"}.GetFilteringExpression(mapping);
```
When I try to get the filtering expression, the `Gridify.GridifyFilteringException: Invalid expression` is thrown.

Would it be possible to add support for this type of nested filtering?

**Comment by alirezanet** [comment]
Hi @MichalVlcek, 
The problem is solved in `v2.7.2`. 

thank you for the feedback.

**Comment by MichalVlcek** [comment]
Hello, thanks for quick reaction and fix!

The expression is now generated properly, but unfortunately filtering using that generated expression still doesn't work.

**Example:**
Mapping and classes are the same as in the example above.
```
var rootList = new List<Root>()
        {
            new Root()
            {
                Child1 = new Child1()
                {
                    Child2List = new List<Child2>()
                    {
                        new Child2() { Name = "name" },
                        new Child2() { Name = "otherName" }
                    }
                }
            }
       };
```
Then calling:
```
rootList.AsQueryable().ApplyFiltering("Child2NameNested=name", mapping).ToList();
```
Throws this exception:
```
System.InvalidOperationException: variable 'x.Child1' of type '….Child1' referenced from scope '', but it is not defined
   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
…
```

**Comment by alirezanet** [comment]
I think I managed to solve the issue, please try `v2.7.3` and let me know if the problem is solved.

thank you

**Comment by MichalVlcek** [comment]
It seems like it works great, thanks :)
